name: Notify ghidra-ci

on:
  push:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-20.04
    steps:
      - name: Create repository dispatch event
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api repos/euprogramador/infra-test/dispatches \
              --raw-field event_type=update-helm-version
