# .github/workflows/chamar-infra.yaml
name: Atualizar versão via infra workflow

on:
  workflow_dispatch:
    inputs:
      new_version:
        required: true
        type: string
      chart_path:
        required: true
        type: string
        default: "dev/values.yaml"

jobs:
  call-infra:
    uses: euprogramador/infra-test/.github/workflows/reusable-update.yaml@main
    with:
      new_version: ${{ inputs.new_version }}
      chart_path: ${{ inputs.chart_path }}
    permissions:
      contents: write
      pull-requests: write
